# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='meilleur_diplome',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidat',
            name='email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='nom_prenom',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='telephone',
            field=models.CharField(max_length=500),
        ),
    ]
