# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0002_auto_20170719_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='meilleur_experience',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidat',
            name='point_clef_sur_l_offre',
            field=models.CharField(default='0', max_length=500),
            preserve_default=False,
        ),
    ]
